### PR TITLE
Snakegame With Javascript

### PR DESCRIPTION
**Pull request by deepsingh132**

### CODE REVIEW

**Comment by skohan** [comment]
It is showing blank screen on my browser, please add screenshots and more information in README

**Review by skohan — CHANGES_REQUESTED** [review]
Please share screenshots of the game. It is showing blank in my browser

**Comment by deepsingh132** [comment]
Yes, sorry for inconvenience doing it now.

**Comment by skohan** [comment]
Good work @deepsingh132 , you can increase the size of the game and align it to the center of the page. And show the score of the player when the game finishes. Just need to README.md explaining how to run and add screenshots of the game, and I'll merge it

**Comment by deepsingh132** [comment]
Thank you , I'm on it.

**Comment by deepsingh132** [comment]
Done. Please don't close this Pr as it is one of my entries in hacktoberfest challenge.

**Comment by skohan** [comment]
Yeah sure. If you can restart the game after showing the player score for 3-4 seconds, it'll be cool

**Comment by deepsingh132** [comment]
> Yeah sure. If you can restart the game after showing the player score for 3-4 seconds, it'll be cool

Yes I'll be adding that up tonight. Can you please add the hacktoberfest label on my pull request.
I'm sorry if I'm asking for too much. You could also merge the pr tomorrow after tonight's commit. Thanks a lot in advance 😄

**Pull request merged**
